- installer/common.sh
- installer/install2.sh
- src/10-ConsolePi.rules
- src/PyConsolePi/common.py
- src/PyConsolePi/power.py
- src/autohotspotN
- src/consolepi-menu.py
- src/j2render.py
This not only adds the ability to add from the menu but also supports more use cases, i.e. pigtail adapters that present a single serial number for all pigtails, or adapters w/ no serial added ... the latter getting an alias assigned to the USB port not the adapter.
> Add Adapter aliases or rename from menu

- src/consolepi-menu.py
When menu is launched on a remote to rename... it was still pointed to the temporary dev menu.
> fix remote rename (still pointed to dev menu)

- .static.yaml
- README.md
- src/consolepi-commands/consolepi-logs
- src/consolepi-commands/consolepi-menu
- src/consolepi-wlanreset.sh
- src/pypkg/consolepi/exec.py
- src/pypkg/consolepi/local.py
- src/systemd/consolepi-mdnsbrowse.service
- src/systemd/consolepi-mdnsreg.service
This update fixes the local.loc_home attribute which was not reflecting the real users home dir impacting validation of existence/creation of ssh-keys for the real user in the key menu
mdns related service files add restart on-failure option (with throttling)
overhaul consolepi-logs added spt for integer argument which will result in tail of # off lines from consolepi.log
> fix loc_home dir attribute, add options to consolepi-log mdns daemon restart on failure

- src/pypkg/consolepi/config.py
- src/pypkg/consolepi/exec.py
Not exactly sure what state causes it, "linked" outlets are derived
from "defined" outlets, but hit TypeError on line 81 as outlet
was NoneType.  Hit it twice, (wsl -> remote) then in new menu
session to debug could not re-create.
> Handle rare issue in Auto Power On

- README.md
- readme_content/power.md
- src/consolepi-menu.py
- src/pypkg/consolepi/config.py
- src/pypkg/consolepi/consolepi.py
- src/pypkg/consolepi/exec.py
- src/pypkg/consolepi/local.py
- src/pypkg/consolepi/menu.py
- src/pypkg/consolepi/power/outlets.py
- src/pypkg/consolepi/udevrename.py
regression at some point, restore logic to check for and launch `empty_menu`
Plus some flak8 formatting
This commit also adds esphome powerstrip support in power menu
If the esphome strip has multiple outlets, and not all of them are linked, or if it has 8 outlets exactly then it
will show in the dli menu.  The 8 outlet thing seems odd, but most dlis are 8 relays, and they show up in the menu regardless.
> fix: ValueError on 'Launching ConsolePi Serial Console Menu' #117

- src/pypkg/consolepi/udevrename.py
lame adapters has  sub-menu which calls menu.py, but this was not re-factored
resolve #121
> fix: rename lame adapters

- src/pypkg/consolepi/udevrename.py
Resolve #120 `consolepi-addconsole` broke after menu redesign to support paging.
> fix #120 rename exception when called directly via consolepi-addconsole

- src/consolepi-menu.py
- src/pypkg/consolepi/menu.py
A remote ConsolePi with no local adapters would fail to launch rename menu (you can rename remotes).
Also re-fixed rename when you changed the baud rate, which broke with the new (added paging support and option to hide the legend for more screen real-estate)
> Minor Fixes

- installer/config.sh
Selecting N to Are Values Correct during validation
Would only present new prompts when a new prompts when a new prompt was
added as a result of the upgrade.
set selected_prompts=false at start of verify() ... when collect() runs
all prompts will be displayed.
> [fix] Installer settings changes

- .gitignore
- .static.yaml
- installer/install.sh
- installer/requirements.txt
- src/btconnect.sh
- src/pypkg/consolepi/menu.py
venv change in behavior on newer python versions to install bin in venv/local/bin vs venv/bin
bcrypt 4 implemented in Rust pin requirement until wheels available or meeting tool-chain to build wheel is less problematic
> handle bcrypt implemented w rust and venv change

- .static.yaml
- src/pypkg/consolepi/__init__.py
- src/pypkg/consolepi/config.py
- Detect vscode and update environment (update PATH as vscode no longer provides full PATH)
- MAJOR FIX, if you have ser2netv4 installed, but still have the v3 conf file in /etc/ser2net.conf
> v2022-4-1  Critical fix if ser2netv4 installed, but ser2netv3 conf file still exists

- .static.yaml
- installer/requirements.txt
:bug: FastAPI isn't forcing pydantic version high enough. Utilizes MultiHostDsn introduced in 1.10.0, but FastAPI not requiring
> installer v68 update requirements

- .static.yaml
- src/autohotspotN
🐛 fix feature added in :bookmark: v2023-6.5 ... leave ip_forwarding enabled
if user has it configured for other purposes. #176
> :bookmark: v2023-6.6

- .static.yaml
- installer/consolepi-image-creator.sh
- installer/install.sh
- installer/requirements.txt
Should resolve #180 pydantic was pinned to avoid this issue, but was listed after FastAPI which uses it, but doesn't pin a version, which results in the most current (pydantic v2).  pydantic v2 is built on Rust, and currently lacks a pre-built wheel for raspberry Pi.  The environment pre-reqs to build it are more cumbersome than it's worth.  The Pin for pydantic was part of a previous release, but apparently not tested on a fresh install, as it was not in the correct position in the requirements file to be effective.
⚠️ This fix has not been tested on a fresh install.  Highly confident it should resolve the issue, getting it pushed now, as the issue breaks all fresh installs.  Will test shortly.
> 🐛 Move pinned pydantic requirement before FastAPI

- .static.yaml
- installer/install.sh
- Change is really only to the installer.  Change to using apt to install python3-virtualenv as pip installing into the system env is no longer allowed per PEP 668
> 🔖 v2023-1.0 Installer v70

- .static.yaml
- installer/config.sh
:bug: prompt for auto hotspot during install was displaying the wrong interface (would show the wired iface vs the wlan)
This had no impact on functionality, the error was limited to the prompt.
> :bookmark: installer v81 minor fix to confirmation prompt

- installer/config.sh
- installer/install.sh
the --silent switch was not preventing all prompts to be blocked. (interactive mode)
--no-users did not prevent the call of the prompt to decide weather users need to be added.
'continue' is a keyword in bash
> install without prompts

- .static.yaml
- README.md
- changelog.md
- installer/common.sh
- installer/install.sh
- installer/requirements.txt
- installer/update.sh
- pyproject.toml
- src/consolepi-commands/consolepi-status
- 📌 pin cryptography they've pushed a release with failed build (43.0.3 fails build on piwheels)
- 🔖 Installer v83
- ✨ add flag for installer to skip Bluetooth setup
- ✨ show model info for non rpi if possible
- 💬 Simplify `consolepi-status` output.
- 📝 Documentation updates/improvements
> 🔖 v2024-3.4 Installer v83

- .static.yaml
- installer/install.sh
- pyproject.toml
- src/consolepi-commands/consolepi-status
- src/consolepi-menu.py
- src/pypkg/consolepi/local.py
- src/pypkg/consolepi/power/dlirest.py
- 🩹 restore cpu serial for rpi
- 👽️update systemctl flags in `consolepi-status` due to deprecation of previously used flag.
- ⚡️Add `--prefer-binary` flag to pip install/upgrade so wheel is used when available (even if it's an older version)
> 🔖 v2024-3.5

- .static.yaml
- installer/config.sh
- installer/requirements.txt
- installer/update.sh
- pyproject.lock
- pyproject.toml
- src/j2/static.nmconnection.j2
- src/pypkg/consolepi/remotes.py
- 🦺 ensure wlan_ip / wired_ip has value when using consolepi-upgrade.  Rare occasion where user changes ConsolePi.yaml to `wired_dhcp: true`, but does not update the config with IP addresses.
- 🔊 fix wired_dhcp log referencing wrong interface in log (wrong variable)
- ♻️ change logic in disable wired dhcp fore NM
- 🩹 remove static fallback file if wired_dhcp=false and they have the old template
- 🔧 Update wired static fallback.  set autoconnect priority to lowest possible.
- 🐛fixes bug re disabling static fallback.
- ⬆️ upgrade aiohttp dep
- 📌 create lock file to appease dependabot
> 🔖 v2024-3.6  Installer v84
